# 开发环境配置
#使用jasypt对数据库连接加密
server:
  # 服务器的HTTP端口，默认为8080
  port: 8082
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
spring:

  datasource:
    url: jdbc:mysql://localhost/hb_datayun?useUnicode=true&characterEncoding=UTF-8&useSSL=FALSE&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
###pub server Link:
#    url: ENC(tbE1nslh0WSV6kiNHdXWgcuKGrqP7JaASKcOpBvjsI0EkuI6QH0uCq8x4K+ObL1nj08dJ4405iD9NoXxuezBFTJWT2T0zXqjRl+9Dd/Q+epFiECaAm+nq6H7IphXitYjV33q0n9V5D+1tdnSletNvQ==)
#      username: ENC(3GVCUjbAQbZoFec6n9moBQ==)
#      password: ENC(5YrWpYWyJPrGRlscjW4aPs7eTiaa5ntZ)

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 5
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的 filters，去掉后监控界面 sql 无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: druidadmin
        login-password: asdfz12308sef
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # 文件上传

  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

mybatis-plus:
  #扫描mapper.xml文件内resultMap的type或者parameterType的pojo，例如 resultType="cn.ytgs.parkingservice.bean.User"配置后为 resultType="User"
  type-aliases-package: cn.best.approveservice.entity

  #扫描dao层xml问件
  mapper-locations: classpath:mapper/*.xml



logging:
  level:
    cn.best.approveservice.dao: debug

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  pageSizeZero: true
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: true
#跨域请求地址
CorsFilter:
  allowOrigin: http://localhost:60383

